name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    # Runs at midnight every day
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.Bhargavml }}
          outputs: dist/snake.svg

      # Upload the animation to the output branch
      - name: Commit and Push Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
